const SUPER_SECRET_CRYPTO_KEY = "asdklufhsadlaklsjdfhaslkdjfhwiklaujhasdlkfjhasdlkfhlaskdljfhasldkjfhaslkdjhf"
const SUPER_SECRET_AZURE_KEY = "254b751d30d74101bf6994f74a3c5c34"
const SUPER_SECRET_FIREBASE_KEY = "AIzaSyD2TF3qwV0gXZ7YPvagpymcuWTMJazIGxc"
export { SUPER_SECRET_CRYPTO_KEY, SUPER_SECRET_AZURE_KEY, SUPER_SECRET_FIREBASE_KEY}