const SUPER_SECRET_CRYPTO_KEY = "***REMOVED***"
const SUPER_SECRET_AZURE_KEY = "***REMOVED***"
const SUPER_SECRET_FIREBASE_KEY = "***REMOVED***"
export { SUPER_SECRET_CRYPTO_KEY, SUPER_SECRET_AZURE_KEY, SUPER_SECRET_FIREBASE_KEY}